# Generated by Django 5.1.7 on 2025-03-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.FloatField()),
                ("processId", models.IntegerField()),
                ("threadId", models.IntegerField()),
                ("parentProcessId", models.IntegerField()),
                ("userId", models.IntegerField()),
                ("mountNamespace", models.IntegerField()),
                ("processName", models.CharField(max_length=255)),
                ("hostName", models.CharField(max_length=255)),
                ("eventId", models.IntegerField()),
                ("eventName", models.CharField(max_length=255)),
                ("stackAddresses", models.JSONField()),
                ("argsNum", models.IntegerField()),
                ("returnValue", models.IntegerField()),
                ("args", models.JSONField()),
                ("sus", models.IntegerField()),
                ("evil", models.IntegerField()),
                ("prediction", models.IntegerField()),
                ("prediction_timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
